# Generated by Django 4.1.5 on 2023-03-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sd", "0002_alter_game_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=5, null=True)),
                ("full_name", models.CharField(max_length=120)),
                ("game_mode", models.CharField(max_length=15)),
            ],
        ),
    ]
