# Generated by Django 4.1.5 on 2023-03-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sd", "0003_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationGameMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sd.game"),
                ),
                (
                    "map",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sd.map"),
                ),
            ],
        ),
    ]
