# Generated by Django 4.1.5 on 2023-03-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sd", "0004_relationgamemap"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("id", "username", "discord_handler"),
                name="Only one person with same name+discord account",
            ),
        ),
    ]
